import argparse
import json
from pathlib import Path
import pprint
import sys
from typing import Optional

def load_id2bus_map(json_file: str | Path) -> dict[str, set[str]]:
    with Path(json_file).open("r", encoding="utf-8") as fp:
        data = json.load(fp)

    if not isinstance(data, list):
        raise ValueError("id2bus JSON root must be a list.")

    result: dict[str, set[str]] = {}
    for idx, item in enumerate(data, start=1):
        if not isinstance(item, dict):
            raise ValueError(f"id2bus[{idx}] must be an object.")

        can_id = item.get("id")
        buses = item.get("buses")
        if not isinstance(can_id, str):
            raise ValueError(f"id2bus[{idx}].id must be a string.")
        if not isinstance(buses, list) or not all(isinstance(x, str) for x in buses):
            raise ValueError(f"id2bus[{idx}].buses must be a list[str].")

        result[normalize_canid(can_id)] = set(buses)

    return result

def normalize_canid(value: str) -> str:
        return value.strip().upper()

def parse_asc_frame(line: str) -> Optional[tuple[str, str]]:
    parts = line.strip().split()
    if not parts or len(parts) < 7:
        return None
    
    try:
        # Currently, CANXL frames are not supported
        if parts[1] == "CANFD":
            # CANFD
            bus_number = parts[2]
            canid = parts[4]
        else:
            # Classic CAN
            bus_number = parts[1]
            canid = parts[2]
        return bus_number, canid
    except (IndexError):
        return None

def narrow_bus_candidates(input_asc: str, id2bus_json: str, unique_label: bool, max_frames: int):
    id2bus = load_id2bus_map(id2bus_json) 
    states: dict[str, dict] = {}

    with Path(input_asc).open("r", encoding="utf-8") as fp:
        passed_line_cnt = 0
        for line_no, line in enumerate(fp, start=1):
            if line_no > max_frames + passed_line_cnt:
                break

            parsed = parse_asc_frame(line)
            if parsed is None:
                passed_line_cnt += 1
                continue

            bus_number, can_id = parsed
            mapped_labels = id2bus.get(can_id)
            if mapped_labels is None:
                continue

            state = states.get(bus_number)
            if state is None:
                states[bus_number] = {
                    "bus_number": bus_number,
                    "candidates": set(mapped_labels),
                    "seen_ids": [can_id]
                }
                continue

            state["candidates"] &= mapped_labels
            if can_id not in state["seen_ids"]:
                state["seen_ids"].append(can_id)
    
    if unique_label:
        changed = True
        while changed:
            changed = False
            resolved_labels = {
                sorted(state["candidates"])[0]
                for state in states.values()
                if len(state["candidates"]) == 1
            }

            for state in states.values():
                if len(state["candidates"]) <= 1:
                    continue

                before = set(state["candidates"])
                after = before - resolved_labels

                if before != after:
                    state["candidates"] = after
                    changed = True

    return states 

def resolve_bus_labels(input_asc: str, id2bus_json: str, unique_label: bool, max_frames: int) -> list[dict]:
    states = narrow_bus_candidates(input_asc, id2bus_json, unique_label, max_frames)
    
    results: list[dict] = []
    for bus_number in sorted(states.keys(), key=lambda x: int(x)):
        state = states[bus_number]
        labels = sorted(state["candidates"])

        if len(labels) == 1:
            resolved = "yes"
        else:
            resolved = "no"

        results.append(
            {
                "bus_number": bus_number,
                "resolved": resolved,
                "labels": labels,
                "seen_ids": state["seen_ids"],
            }
        )

    return results

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input_asc", help="Input ASC file")
    parser.add_argument("id2bus_json", help="JSON file generated by generate_id2bus_map.py")
    parser.add_argument("-O", "--output", help="output file")
    parser.add_argument("-u", "--unique-label", action="store_true", help="if true, assume that the bus appears on only one interface")
    parser.add_argument("-m", "--max-frames", type=int, default=10000, help="Maximum number of ASC frames to read")
    args = parser.parse_args()

    asc_busmap = resolve_bus_labels(args.input_asc, args.id2bus_json, args.unique_label, args.max_frames) 

    if args.output:
        with open(args.output, "w", encoding="utf-8") as fp:
            json.dump(asc_busmap, fp, ensure_ascii=False, indent=2)
    else:
        pprint.pprint(asc_busmap)

    return 0

if __name__ == '__main__':
    sys.exit(main())